name = "Sisyphus Proxy"
port = 80

[load_cert]
load = false
keyfile="./.certs/private_key.pem"
certfile="./.certs/certificate.pem" 

[security]
cookie = "nothin..."


[cors]
use_cors = true
allow_origin = ["*"]
allow_credentials = true
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["Content-Type", "Authorization"]
max_age = 3600
expose_headers = ["X-My-Custom-Header"]

[security.basic_auth]
username = "admin"
password = "password"
realm = "Sisyphus Proxy"

[logging]
level = "info"
logfile = "./logs/sisyphus.log"

[cache]
enable_cache = false
cache_dir = "./cache"
cache_duration = 3600
